CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  email text,
  role USER-DEFINED NOT NULL DEFAULT 'commuter'::app_role,
  contact_number text,
  address text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.rider_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  public_id text NOT NULL UNIQUE,
  public_name text NOT NULL,
  business_permit_reference text,
  service_area text,
  verification_status USER-DEFINED NOT NULL DEFAULT 'Pending'::verification_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  full_name text DEFAULT ''::text,
  ally_group text DEFAULT ''::text,
  plate_number text DEFAULT ''::text,
  address text DEFAULT ''::text,
  license_no text DEFAULT ''::text,
  license_expiry text DEFAULT ''::text,
  or_cr_name text DEFAULT ''::text,
  make text DEFAULT ''::text,
  contact_no text DEFAULT ''::text,
  remarks text DEFAULT ''::text,
  source_no text DEFAULT ''::text,
  source_association text DEFAULT ''::text,
  qr_token uuid DEFAULT gen_random_uuid(),
  average_rating numeric,
  CONSTRAINT rider_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT rider_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.rider_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rider_id uuid NOT NULL,
  reviewed_by uuid,
  status USER-DEFINED NOT NULL,
  review_note text,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rider_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT rider_verifications_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.rider_profiles(id),
  CONSTRAINT rider_verifications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.fare_matrix_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  version_code text NOT NULL,
  minimum_distance numeric NOT NULL CHECK (minimum_distance > 0::numeric),
  maximum_distance numeric NOT NULL,
  regular_fare numeric NOT NULL CHECK (regular_fare >= 0::numeric),
  discounted_fare numeric NOT NULL CHECK (discounted_fare >= 0::numeric),
  effective_from timestamp with time zone,
  effective_until timestamp with time zone,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fare_matrix_versions_pkey PRIMARY KEY (id),
  CONSTRAINT fare_matrix_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.fare_calculations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  pickup text NOT NULL,
  dropoff text NOT NULL,
  pickup_lat numeric NOT NULL,
  pickup_lng numeric NOT NULL,
  dropoff_lat numeric NOT NULL,
  dropoff_lng numeric NOT NULL,
  distance_km numeric NOT NULL CHECK (distance_km > 0::numeric),
  regular_fare numeric NOT NULL CHECK (regular_fare >= 0::numeric),
  discounted_fare numeric NOT NULL CHECK (discounted_fare >= 0::numeric),
  fare_matrix_version uuid,
  routing_provider text NOT NULL DEFAULT 'OSRM'::text,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  timestamp timestamp with time zone,
  CONSTRAINT fare_calculations_pkey PRIMARY KEY (id),
  CONSTRAINT fare_calculations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT fare_calculations_fare_matrix_version_fkey FOREIGN KEY (fare_matrix_version) REFERENCES public.fare_matrix_versions(id)
);
CREATE TABLE public.ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  commuter_id uuid NOT NULL,
  rider_id uuid NOT NULL,
  professionalism smallint NOT NULL CHECK (professionalism >= 1 AND professionalism <= 5),
  safety smallint NOT NULL CHECK (safety >= 1 AND safety <= 5),
  punctuality smallint NOT NULL CHECK (punctuality >= 1 AND punctuality <= 5),
  service_quality smallint NOT NULL CHECK (service_quality >= 1 AND service_quality <= 5),
  comment text CHECK (char_length(comment) <= 500),
  trip_reference text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ratings_pkey PRIMARY KEY (id),
  CONSTRAINT ratings_commuter_id_fkey FOREIGN KEY (commuter_id) REFERENCES public.profiles(id),
  CONSTRAINT ratings_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.rider_profiles(id)
);
CREATE TABLE public.incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reference_no text NOT NULL UNIQUE,
  complainant_id uuid NOT NULL,
  rider_reference text,
  category text NOT NULL CHECK (category = ANY (ARRAY['overcharging'::text, 'refuse-discount'::text, 'rude-conduct'::text, 'unsafe-driving'::text, 'other'::text])),
  incident_datetime timestamp with time zone NOT NULL,
  location_text text,
  description text NOT NULL CHECK (char_length(description) >= 5 AND char_length(description) <= 5000),
  status USER-DEFINED NOT NULL DEFAULT 'New'::report_status,
  administrative_note text,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT incidents_pkey PRIMARY KEY (id),
  CONSTRAINT incidents_complainant_id_fkey FOREIGN KEY (complainant_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  action text NOT NULL,
  target_type text,
  target_id text,
  previous_value jsonb,
  new_value jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_id uuid,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.safety_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  severity text NOT NULL DEFAULT 'info'::text,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'New'::text CHECK (status = ANY (ARRAY['New'::text, 'Acknowledged'::text, 'Responded'::text, 'Resolved'::text, 'Dismissed'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reference_no text,
  CONSTRAINT safety_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT safety_alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);